[project]
name = "mqs-molecule-generation"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "yeray142", email = "yeraycorderocarrasco@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
]

[project.scripts]
mqs-molecule-generation = "mqs_molecule_generation:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
